"use-client"

// UI
import { Geist, Geist_Mono } from "next/font/google";
import "./ui/globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";

// Leatflet necesita archivo css para verse
import "leaflet/dist/leaflet.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// Componentes Propios
import Nav from "./ui/nav/Nav";
import Footer from "./ui/footer/Footer";

// Metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


/* -- MAIN -- */
export default function RootLayout({ children }) {

  return (

    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <Nav />

        {children}

        <Footer />
        
      </body>

    </html>
  );
}